trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

variables:
  imageName: 'bredenoordiot/test'

steps:
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2

